# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'mobility-squad'

menu:
- {name: 'Companies',          url: 'companies'}
- {name: 'Projects',           url: 'projects'}
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/mobility_squad'}
# - {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
- {icon: 'instagram', link:  'https://instagram.com/mobilitysquad'}
- {icon: 'envelope', link:   'mailto:m.j.broekhuijsen@tue.nl'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Related projects:'

project_date_prefix: 'Published on'
